<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/models/plane/scene.gltf
Author: AntijnvanderGun (https://sketchfab.com/AntijnvanderGun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ww1-plane-c4edeb0e410f46e8a4db320879f0a1db
Title: Stylized WW1 Plane
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/plane/scene.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <T.Group name="365f4c91b47842d8b66a5eecbcbdb59dfbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="polySurface172" position={[-0.83, 5.81, -1.09]} rotation={[0.01, 0.04, -0.06]}>
                <T.Group name="polySurface171" position={[0, -0.57, 14.21]} rotation={[0, 0, -2.64]}>
                  <T.Group name="polySurface304" position={[0, -3.3, -12.84]}>
                    <T.Mesh
                      name="polySurface304_pasted__lambert2_0"
                      geometry={gltf.nodes.polySurface304_pasted__lambert2_0.geometry}
                      material={gltf.materials.pasted__lambert2}
                    />
                  </T.Group>
                  <T.Group name="polySurface305" position={[0, -3.3, -12.84]}>
                    <T.Mesh
                      name="polySurface305_pasted__lambert2_0"
                      geometry={gltf.nodes.polySurface305_pasted__lambert2_0.geometry}
                      material={gltf.materials.pasted__lambert2}
                    />
                  </T.Group>
                  <T.Group name="polySurface306" position={[0, -3.3, -12.84]}>
                    <T.Mesh
                      name="polySurface306_pasted__lambert2_0"
                      geometry={gltf.nodes.polySurface306_pasted__lambert2_0.geometry}
                      material={gltf.materials.pasted__lambert2}
                    />
                  </T.Group>
                  <T.Group name="transform140" position={[0, -3.3, -12.84]} />
                  <T.Group name="polySurface406" position={[0, 0.01, -0.61]}>
                    <T.Mesh
                      name="polySurface406_Tooner_0"
                      geometry={gltf.nodes.polySurface406_Tooner_0.geometry}
                      material={gltf.materials.Tooner}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="pCube1" position={[0, -0.57, 13.29]} rotation={[0, 0, 2.32]} scale={14.59}>
                  <T.Mesh
                    name="pCube1_Blur_effect_0"
                    geometry={gltf.nodes.pCube1_Blur_effect_0.geometry}
                    material={gltf.materials.Blur_effect}
                  />
                </T.Group>
                <T.Group name="pCube4" position={[0, -0.57, 13.07]} rotation={[0, 0, 2.24]} scale={9.32}>
                  <T.Mesh
                    name="pCube4_Blur_effect_0"
                    geometry={gltf.nodes.pCube4_Blur_effect_0.geometry}
                    material={gltf.materials.Blur_effect}
                  />
                </T.Group>
                <T.Group name="polySurface173" position={[-11.65, -1.36, 1.22]} rotation={[-0.07, 0, 0]}>
                  <T.Group name="pCube7" position={[-1.08, -0.01, -2.1]}>
                    <T.Mesh
                      name="pCube7_lambert1_0"
                      geometry={gltf.nodes.pCube7_lambert1_0.geometry}
                      material={gltf.materials.lambert1}
                    />
                  </T.Group>
                  <T.Group name="polySurface407" position={[11.65, -2.42, 0.38]} rotation={[-0.06, 0, 0]}>
                    <T.Mesh
                      name="polySurface407_Tooner_0"
                      geometry={gltf.nodes.polySurface407_Tooner_0.geometry}
                      material={gltf.materials.Tooner}
                    />
                  </T.Group>
                  <T.Mesh
                    name="polySurface173_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface173_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface174" position={[11.65, -1.4, 1.15]} rotation={[0.08, 0, 0]}>
                  <T.Group name="pCube6" position={[1.37, 0.05, -2.02]} scale={[1, 1, 1.04]}>
                    <T.Mesh
                      name="pCube6_lambert1_0"
                      geometry={gltf.nodes.pCube6_lambert1_0.geometry}
                      material={gltf.materials.lambert1}
                    />
                  </T.Group>
                  <T.Group name="polySurface408" position={[-11.65, -2.38, 0.46]} rotation={[-0.06, 0, 0]}>
                    <T.Mesh
                      name="polySurface408_Tooner_0"
                      geometry={gltf.nodes.polySurface408_Tooner_0.geometry}
                      material={gltf.materials.Tooner}
                    />
                  </T.Group>
                  <T.Mesh
                    name="polySurface174_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface174_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface182" position={[-0.02, 3.62, 4.33]} rotation={[-0.11, 0, 0]}>
                  <T.Group name="polySurface165" position={[-12.34, 1.3, -3.48]} rotation={[3.13, 0, 0]} scale={-1}>
                    <T.Group name="pCube8" position={[1.7, -0.02, -1.87]}>
                      <T.Mesh
                        name="pCube8_lambert1_0"
                        geometry={gltf.nodes.pCube8_lambert1_0.geometry}
                        material={gltf.materials.lambert1}
                      />
                    </T.Group>
                    <T.Group name="transform138" position={[-12.36, -8.49, 0.83]} rotation={[3.08, 0, 0]} scale={-1} />
                    <T.Group name="polySurface410" position={[-12.36, -8.49, 0.83]} rotation={[3.08, 0, 0]} scale={-1}>
                      <T.Mesh
                        name="polySurface410_Tooner_0"
                        geometry={gltf.nodes.polySurface410_Tooner_0.geometry}
                        material={gltf.materials.Tooner}
                      />
                    </T.Group>
                    <T.Mesh
                      name="polySurface165_pasted__lambert2_0"
                      geometry={gltf.nodes.polySurface165_pasted__lambert2_0.geometry}
                      material={gltf.materials.pasted__lambert2}
                    />
                  </T.Group>
                  <T.Group name="polySurface161" position={[12.39, 1.3, -3.44]} rotation={[0.17, 0, 0]}>
                    <T.Group name="pCube5" position={[1.8, 0.08, -1.88]} scale={[1, 1, 0.87]}>
                      <T.Mesh
                        name="pCube5_lambert1_0"
                        geometry={gltf.nodes.pCube5_lambert1_0.geometry}
                        material={gltf.materials.lambert1}
                      />
                    </T.Group>
                    <T.Group name="polySurface411" position={[-12.36, -8.49, 0.79]} rotation={[-0.06, 0, 0]}>
                      <T.Mesh
                        name="polySurface411_Tooner_0"
                        geometry={gltf.nodes.polySurface411_Tooner_0.geometry}
                        material={gltf.materials.Tooner}
                      />
                    </T.Group>
                    <T.Mesh
                      name="polySurface161_pasted__lambert2_0"
                      geometry={gltf.nodes.polySurface161_pasted__lambert2_0.geometry}
                      material={gltf.materials.pasted__lambert2}
                    />
                  </T.Group>
                  <T.Group name="polySurface409" position={[0.02, -7.22, -3.17]}>
                    <T.Mesh
                      name="polySurface409_Tooner_0"
                      geometry={gltf.nodes.polySurface409_Tooner_0.geometry}
                      material={gltf.materials.Tooner}
                    />
                  </T.Group>
                  <T.Mesh
                    name="polySurface182_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface182_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="pCube10" position={[-6.25, 0.64, -12.78]}>
                  <T.Mesh
                    name="pCube10_lambert1_0"
                    geometry={gltf.nodes.pCube10_lambert1_0.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group name="pCube9" position={[6.6, 0.66, -12.57]}>
                  <T.Mesh
                    name="pCube9_lambert1_0"
                    geometry={gltf.nodes.pCube9_lambert1_0.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group name="pCube11" position={[0.03, 5.29, -12.12]}>
                  <T.Mesh
                    name="pCube11_lambert1_0"
                    geometry={gltf.nodes.pCube11_lambert1_0.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group name="polySurface187" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface187_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface187_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface188" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface188_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface188_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface189" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface189_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface189_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface190" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface190_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface190_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface191" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface191_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface191_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface192" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface192_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface192_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface193" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface193_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface193_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface194" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface194_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface194_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface195" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface195_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface195_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface196" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface196_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface196_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface197" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface197_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface197_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface198" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface198_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface198_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface199" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface199_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface199_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface200" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface200_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface200_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface201" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface201_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface201_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface202" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface202_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface202_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface203" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface203_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface203_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface204" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface204_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface204_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface205" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface205_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface205_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface206" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface206_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface206_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface207" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface207_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface207_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface208" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface208_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface208_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface209" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface209_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface209_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface210" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface210_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface210_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface211" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface211_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface211_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface212" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface212_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface212_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface213" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface213_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface213_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface214" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface214_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface214_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface215" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface215_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface215_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface216" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface216_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface216_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface217" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface217_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface217_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface218" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface218_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface218_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface219" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface219_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface219_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface220" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface220_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface220_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface221" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface221_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface221_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface222" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface222_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface222_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface223" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface223_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface223_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface224" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface224_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface224_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface225" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface225_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface225_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface226" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface226_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface226_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface227" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface227_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface227_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface228" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface228_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface228_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface229" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface229_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface229_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface230" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface230_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface230_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface231" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface231_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface231_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface232" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface232_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface232_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface233" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface233_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface233_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface234" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface234_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface234_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface235" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface235_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface235_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface236" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface236_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface236_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface237" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface237_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface237_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface238" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface238_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface238_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface239" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface239_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface239_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface240" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface240_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface240_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface241" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface241_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface241_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface242" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface242_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface242_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface243" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface243_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface243_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface244" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface244_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface244_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface245" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface245_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface245_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface246" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface246_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface246_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface247" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface247_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface247_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface248" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface248_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface248_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface249" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface249_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface249_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface250" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface250_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface250_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface251" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface251_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface251_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface252" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface252_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface252_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface253" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface253_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface253_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface254" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface254_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface254_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface255" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface255_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface255_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface256" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface256_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface256_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface257" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface257_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface257_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface258" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface258_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface258_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface259" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface259_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface259_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface260" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface260_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface260_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface261" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface261_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface261_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface262" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface262_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface262_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface263" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface263_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface263_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface264" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface264_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface264_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface265" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface265_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface265_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface266" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface266_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface266_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface267" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface267_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface267_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface268" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface268_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface268_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface269" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface269_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface269_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface270" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface270_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface270_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface271" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface271_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface271_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface272" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface272_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface272_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface273" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface273_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface273_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface274" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface274_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface274_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface275" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface275_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface275_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface276" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface276_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface276_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface277" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface277_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface277_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface278" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface278_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface278_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface279" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface279_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface279_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface280" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface280_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface280_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface281" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface281_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface281_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface282" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface282_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface282_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface283" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface283_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface283_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface284" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface284_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface284_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface285" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface285_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface285_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface286" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface286_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface286_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface287" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface287_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface287_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface288" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface288_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface288_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface289" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface289_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface289_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface290" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface290_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface290_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface291" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface291_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface291_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface292" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface292_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface292_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface293" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface293_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface293_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface294" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface294_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface294_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface295" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface295_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface295_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface296" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface296_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface296_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface297" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface297_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface297_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface298" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface298_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface298_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface299" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface299_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface299_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface300" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface300_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface300_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface301" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface301_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface301_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface302" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface302_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface302_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="polySurface303" position={[0, -3.87, 1.37]}>
                  <T.Mesh
                    name="polySurface303_pasted__lambert2_0"
                    geometry={gltf.nodes.polySurface303_pasted__lambert2_0.geometry}
                    material={gltf.materials.pasted__lambert2}
                  />
                </T.Group>
                <T.Group name="transform139" position={[0, -3.87, 1.37]} />
                <T.Group name="polySurface308" position={[0, 0.09, 0.04]}>
                  <T.Mesh
                    name="polySurface308_Tooner_0"
                    geometry={gltf.nodes.polySurface308_Tooner_0.geometry}
                    material={gltf.materials.Tooner}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="polySurface78">
                <T.Group name="transform48" />
              </T.Group>
              <T.Group name="polySurface77">
                <T.Group name="transform46" />
              </T.Group>
              <T.Group name="polySurface76">
                <T.Group name="transform47" />
              </T.Group>
              <T.Group name="polySurface75">
                <T.Group name="transform45" />
              </T.Group>
              <T.Group name="polySurface74">
                <T.Group name="transform27" />
              </T.Group>
              <T.Group name="polySurface73">
                <T.Group name="transform44" />
              </T.Group>
              <T.Group name="polySurface72">
                <T.Group name="transform30" />
              </T.Group>
              <T.Group name="polySurface71">
                <T.Group name="transform99" />
              </T.Group>
              <T.Group name="polySurface70">
                <T.Group name="transform26" />
              </T.Group>
              <T.Group name="polySurface69">
                <T.Group name="transform97" />
              </T.Group>
              <T.Group name="polySurface68">
                <T.Group name="transform15" />
              </T.Group>
              <T.Group name="polySurface67">
                <T.Group name="transform22" />
              </T.Group>
              <T.Group name="polySurface53">
                <T.Group name="transform98" />
              </T.Group>
              <T.Group name="polySurface52">
                <T.Group name="transform20" />
              </T.Group>
              <T.Group name="polySurface51">
                <T.Group name="transform100" />
              </T.Group>
              <T.Group name="polySurface50">
                <T.Group name="transform38" />
              </T.Group>
              <T.Group name="polySurface49">
                <T.Group name="transform35" />
              </T.Group>
              <T.Group name="polySurface48">
                <T.Group name="transform42" />
              </T.Group>
              <T.Group name="polySurface47">
                <T.Group name="transform37" />
              </T.Group>
              <T.Group name="polySurface46">
                <T.Group name="transform41" />
              </T.Group>
              <T.Group name="polySurface45">
                <T.Group name="transform40" />
              </T.Group>
              <T.Group name="polySurface44">
                <T.Group name="transform34" />
              </T.Group>
              <T.Group name="polySurface43">
                <T.Group name="transform36" />
              </T.Group>
              <T.Group name="polySurface42">
                <T.Group name="transform39" />
              </T.Group>
              <T.Group name="polySurface66">
                <T.Group name="transform19" />
              </T.Group>
              <T.Group name="polySurface65">
                <T.Group name="transform43" />
              </T.Group>
              <T.Group name="polySurface64">
                <T.Group name="transform116" />
              </T.Group>
              <T.Group name="polySurface63">
                <T.Group name="transform16" />
              </T.Group>
              <T.Group name="polySurface62">
                <T.Group name="transform118" />
              </T.Group>
              <T.Group name="polySurface61">
                <T.Group name="transform33" />
              </T.Group>
              <T.Group name="polySurface60">
                <T.Group name="transform113" />
              </T.Group>
              <T.Group name="polySurface59">
                <T.Group name="transform120" />
              </T.Group>
              <T.Group name="polySurface58">
                <T.Group name="transform115" />
              </T.Group>
              <T.Group name="polySurface57">
                <T.Group name="transform119" />
              </T.Group>
              <T.Group name="polySurface56">
                <T.Group name="transform114" />
              </T.Group>
              <T.Group name="polySurface55">
                <T.Group name="transform24" />
              </T.Group>
              <T.Group name="polySurface54">
                <T.Group name="transform117" />
              </T.Group>
              <T.Group name="polySurface41">
                <T.Group name="transform71" />
              </T.Group>
              <T.Group name="polySurface40">
                <T.Group name="transform73" />
              </T.Group>
              <T.Group name="polySurface39">
                <T.Group name="transform72" />
              </T.Group>
              <T.Group name="polySurface38">
                <T.Group name="transform75" />
              </T.Group>
              <T.Group name="polySurface37">
                <T.Group name="transform79" />
              </T.Group>
              <T.Group name="polySurface36">
                <T.Group name="transform76" />
              </T.Group>
              <T.Group name="polySurface35">
                <T.Group name="transform70" />
              </T.Group>
              <T.Group name="polySurface34">
                <T.Group name="transform77" />
              </T.Group>
              <T.Group name="polySurface33">
                <T.Group name="transform74" />
              </T.Group>
              <T.Group name="polySurface32">
                <T.Group name="transform78" />
              </T.Group>
              <T.Group name="polySurface31">
                <T.Group name="transform69" />
              </T.Group>
              <T.Group name="polySurface30">
                <T.Group name="transform107" />
              </T.Group>
              <T.Group name="polySurface29">
                <T.Group name="transform109" />
              </T.Group>
              <T.Group name="polySurface11">
                <T.Group name="transform112" />
              </T.Group>
              <T.Group name="polySurface1">
                <T.Group name="transform106" />
              </T.Group>
              <T.Group name="polySurface10">
                <T.Group name="transform101" />
              </T.Group>
              <T.Group name="polySurface7">
                <T.Group name="transform108" />
              </T.Group>
              <T.Group name="polySurface5">
                <T.Group name="transform102" />
              </T.Group>
              <T.Group name="polySurface3">
                <T.Group name="transform103" />
              </T.Group>
              <T.Group name="polySurface8">
                <T.Group name="transform105" />
              </T.Group>
              <T.Group name="polySurface2">
                <T.Group name="transform110" />
              </T.Group>
              <T.Group name="polySurface6">
                <T.Group name="transform111" />
              </T.Group>
              <T.Group name="polySurface9">
                <T.Group name="transform104" />
              </T.Group>
              <T.Group name="polySurface4">
                <T.Group name="transform60" />
              </T.Group>
              <T.Group name="polySurface116">
                <T.Group name="transform61" />
              </T.Group>
              <T.Group name="polySurface115">
                <T.Group name="transform62" />
              </T.Group>
              <T.Group name="polySurface114">
                <T.Group name="transform63" />
              </T.Group>
              <T.Group name="polySurface113">
                <T.Group name="transform64" />
              </T.Group>
              <T.Group name="polySurface112">
                <T.Group name="transform65" />
              </T.Group>
              <T.Group name="polySurface111">
                <T.Group name="transform66" />
              </T.Group>
              <T.Group name="polySurface110">
                <T.Group name="transform18" />
              </T.Group>
              <T.Group name="polySurface109">
                <T.Group name="transform67" />
              </T.Group>
              <T.Group name="polySurface108">
                <T.Group name="transform25" />
              </T.Group>
              <T.Group name="polySurface107">
                <T.Group name="transform68" />
              </T.Group>
              <T.Group name="polySurface106">
                <T.Group name="transform49" />
              </T.Group>
              <T.Group name="polySurface105">
                <T.Group name="transform50" />
              </T.Group>
              <T.Group name="polySurface121">
                <T.Group name="transform51" />
              </T.Group>
              <T.Group name="polySurface120">
                <T.Group name="transform52" />
              </T.Group>
              <T.Group name="polySurface119">
                <T.Group name="transform53" />
              </T.Group>
              <T.Group name="polySurface118">
                <T.Group name="transform54" />
              </T.Group>
              <T.Group name="polySurface117">
                <T.Group name="transform55" />
              </T.Group>
              <T.Group name="polySurface91">
                <T.Group name="transform56" />
              </T.Group>
              <T.Group name="polySurface90">
                <T.Group name="transform57" />
              </T.Group>
              <T.Group name="polySurface89">
                <T.Group name="transform29" />
              </T.Group>
              <T.Group name="polySurface88">
                <T.Group name="transform58" />
              </T.Group>
              <T.Group name="polySurface87">
                <T.Group name="transform59" />
              </T.Group>
              <T.Group name="polySurface86">
                <T.Group name="transform129" />
              </T.Group>
              <T.Group name="polySurface85">
                <T.Group name="transform130" />
              </T.Group>
              <T.Group name="polySurface84">
                <T.Group name="transform131" />
              </T.Group>
              <T.Group name="polySurface83">
                <T.Group name="transform132" />
              </T.Group>
              <T.Group name="polySurface82">
                <T.Group name="transform133" />
              </T.Group>
              <T.Group name="polySurface81">
                <T.Group name="transform134" />
              </T.Group>
              <T.Group name="polySurface80">
                <T.Group name="transform21" />
              </T.Group>
              <T.Group name="polySurface79">
                <T.Group name="transform32" />
              </T.Group>
              <T.Group name="polySurface103">
                <T.Group name="transform23" />
              </T.Group>
              <T.Group name="polySurface102">
                <T.Group name="transform135" />
              </T.Group>
              <T.Group name="polySurface101">
                <T.Group name="transform136" />
              </T.Group>
              <T.Group name="polySurface100">
                <T.Group name="transform121" />
              </T.Group>
              <T.Group name="polySurface99">
                <T.Group name="transform122" />
              </T.Group>
              <T.Group name="polySurface98">
                <T.Group name="transform31" />
              </T.Group>
              <T.Group name="polySurface97">
                <T.Group name="transform123" />
              </T.Group>
              <T.Group name="polySurface96">
                <T.Group name="transform17" />
              </T.Group>
              <T.Group name="polySurface95">
                <T.Group name="transform124" />
              </T.Group>
              <T.Group name="polySurface94">
                <T.Group name="transform125" />
              </T.Group>
              <T.Group name="polySurface93">
                <T.Group name="transform126" />
              </T.Group>
              <T.Group name="polySurface92">
                <T.Group name="transform28" />
              </T.Group>
              <T.Group name="polySurface17">
                <T.Group name="transform127" />
              </T.Group>
              <T.Group name="polySurface16">
                <T.Group name="transform128" />
              </T.Group>
              <T.Group name="polySurface13">
                <T.Group name="transform82" />
              </T.Group>
              <T.Group name="polySurface14">
                <T.Group name="transform83" />
              </T.Group>
              <T.Group name="polySurface15">
                <T.Group name="transform84" />
              </T.Group>
              <T.Group name="polySurface12">
                <T.Group name="transform85" />
              </T.Group>
              <T.Group name="polySurface27">
                <T.Group name="transform86" />
              </T.Group>
              <T.Group name="polySurface25">
                <T.Group name="transform87" />
              </T.Group>
              <T.Group name="polySurface26">
                <T.Group name="transform88" />
              </T.Group>
              <T.Group name="polySurface28">
                <T.Group name="transform89" />
              </T.Group>
              <T.Group name="polySurface24">
                <T.Group name="transform90" />
              </T.Group>
              <T.Group name="polySurface23">
                <T.Group name="transform91" />
              </T.Group>
              <T.Group name="polySurface22">
                <T.Group name="transform92" />
              </T.Group>
              <T.Group name="polySurface21">
                <T.Group name="transform93" />
              </T.Group>
              <T.Group name="polySurface20">
                <T.Group name="transform94" />
              </T.Group>
              <T.Group name="polySurface19">
                <T.Group name="transform80" />
              </T.Group>
              <T.Group name="polySurface18">
                <T.Group name="transform81" />
              </T.Group>
              <T.Group name="polySurface162" position={[48.87, -58.16, -158.56]}>
                <T.Group name="polySurface169" position={[-0.86, 21.73, -3.89]}>
                  <T.Group name="transform95" />
                </T.Group>
              </T.Group>
              <T.Group name="polySurface170">
                <T.Group name="transform96" />
              </T.Group>
              <T.Group name="nucleus1" />
              <T.Group name="polySurface186">
                <T.Group name="transform142" />
              </T.Group>
              <T.Group name="nurbsCircle1" position={[0, 0, -4.2]}>
                <T.Group name="pCube12" position={[27.47, 9.74, -42.13]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0"
                    geometry={gltf.nodes.pCube12_lambert1_0.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle2" position={[-8.75, -5.27, 10.96]}>
                <T.Group name="pCube12_1" position={[27.47, 9.74, -41.48]} scale={0.01}>
                  <T.Mesh
                    name="pCube12_lambert1_0_1"
                    geometry={gltf.nodes.pCube12_lambert1_0_1.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle3" position={[-7.43, 8.26, -16.66]}>
                <T.Group name="pCube12_9" position={[27.47, 9.74, 25.69]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_9"
                    geometry={gltf.nodes.pCube12_lambert1_0_9.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle4" position={[-19.1, 5.53, -0.44]}>
                <T.Group name="pCube12_2" position={[27.47, 9.74, 41.91]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_2"
                    geometry={gltf.nodes.pCube12_lambert1_0_2.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle5" position={[-14.62, -16.61, -6.16]}>
                <T.Group name="pCube12_3" position={[27.47, 9.74, 36.19]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_3"
                    geometry={gltf.nodes.pCube12_lambert1_0_3.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle6" position={[-24.31, -17.68, 1.91]}>
                <T.Group name="pCube12_4" position={[27.47, 9.74, 11.38]} scale={0.89}>
                  <T.Mesh
                    name="pCube12_lambert1_0_4"
                    geometry={gltf.nodes.pCube12_lambert1_0_4.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle7" position={[-27.88, 7.69, 7.91]}>
                <T.Group name="pCube12_10" position={[27.47, 9.74, 50.26]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_10"
                    geometry={gltf.nodes.pCube12_lambert1_0_10.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle8" position={[-40.06, 10.44, -13.22]}>
                <T.Group name="pCube12_5" position={[27.47, 9.74, -10.46]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_5"
                    geometry={gltf.nodes.pCube12_lambert1_0_5.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle9" position={[-48.15, 2.47, 2.45]}>
                <T.Group name="pCube12_6" position={[27.47, 9.74, 36.19]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_6"
                    geometry={gltf.nodes.pCube12_lambert1_0_6.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle10" position={[-38.16, -10.89, -6.16]}>
                <T.Group name="pCube12_7" position={[27.47, 9.74, 36.19]} scale={0}>
                  <T.Mesh
                    name="pCube12_lambert1_0_7"
                    geometry={gltf.nodes.pCube12_lambert1_0_7.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="nurbsCircle11" position={[-46.04, -5.98, -16.95]}>
                <T.Group name="pCube12_8" position={[27.47, 9.74, -22.82]} scale={0.37}>
                  <T.Mesh
                    name="pCube12_lambert1_0_8"
                    geometry={gltf.nodes.pCube12_lambert1_0_8.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
