<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/models/ramsden/ramsden.glb --output ./src/components/Ramsden.svelte
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/ramsden/ramsden.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.top.geometry} material={gltf.materials.wood_table_001} position={[0.4, 0, -0.22]} />
    <T.Mesh
      geometry={gltf.nodes.tube_joins.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.13, 0, -0.07]}
    />
    <T.Mesh geometry={gltf.nodes.Cylinder.geometry} material={gltf.materials.Glass} position={[0.13, 0.12, -0.07]} />
    <T.Mesh
      geometry={gltf.nodes.Circle.geometry}
      material={gltf.materials['Material.001']}
      position={[0.63, 0.36, -0.22]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder001.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.13, 0.36, -0.07]}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube001.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.13, 0.31, -0.07]}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube002.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.47, 0.41, -0.07]}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube003.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.01, 0.36, -0.07]}
    />
    <T.Mesh
      geometry={gltf.nodes.leg.geometry}
      material={gltf.materials.wood_table_001}
      position={[0.01, -0.02, -0.01]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials.wood_table_001}
      position={[0.34, -0.02, -0.01]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane002.geometry}
      material={gltf.materials.wood_table_001}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
    />
    <T.Mesh
      geometry={gltf.nodes.support.geometry}
      material={gltf.materials.wood_table_001}
      position={[0.75, 0.19, -0.22]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials.wood_table_001}
      position={[0.63, 0.01, -0.22]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder002.geometry}
      material={gltf.materials['Used Metal']}
      position={[-0.07, 0.36, -0.22]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube004.geometry}
      material={gltf.materials['Used Metal']}
      position={[-0.04, 0.36, -0.07]}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube005.geometry}
      material={gltf.materials['Used Metal']}
      position={[-0.07, 0.36, -0.07]}
      scale={0.51}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube006.geometry}
      material={gltf.materials['Used Metal']}
      position={[-0.07, 0.36, -0.22]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.02, 0.41, -0.22]}
      rotation={[Math.PI / 2, Math.PI / 6, -Math.PI / 2]}
      scale={[1, 0.59, 0.89]}
    />
    <T.Mesh
      geometry={gltf.nodes.Roundcube007.geometry}
      material={gltf.materials['Used Metal']}
      position={[0.1, 0.46, -0.22]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
